# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 20:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsource',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='feedsource',
            name='date_parsed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
