# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0002_auto_20170827_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedpost',
            old_name='post_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='feedsource',
            old_name='feed_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='feedsource',
            old_name='feed_url',
            new_name='url',
        ),
    ]
