# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0002_auto_20170905_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='feed_sources',
            field=models.ManyToManyField(to='fd.FeedSource'),
        ),
    ]
