# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0003_auto_20170827_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedpost',
            name='id',
        ),
        migrations.AddField(
            model_name='feedpost',
            name='author',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedpost',
            name='url',
            field=models.CharField(default='', max_length=200, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
