# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fd', '0003_feedpost_feed_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsource',
            name='show_on_frontpage',
            field=models.BooleanField(default=True),
        ),
    ]
