name: CI

on:
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@master
#      - uses: actions/setup-python@v1
#        with:
#          python-version: '3.7'
#          architecture: 'x64'
#      - name: Install pg_conf postgresql
#        run: sudo apt-get install libpq-dev 
#      - run: pip install -r requirements/production.txt
#      - name: copy file via ssh key
#        uses: horochx/deploy-via-scp@master
#	uses: actions/checkout@master
#        with:
#          host: ${{ secrets.HOST }}
#          user: ${{ secrets.USERNAME }}  
#          key: ${{ secrets.KEY }}
#          local: "*"
#          remote: "/home/fedry/dj"
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: fab -f dj/fabfile.py production deploy
